# Generated by Django 4.2 on 2023-04-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_alter_categorymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productimage',
            field=models.ImageField(upload_to='static/assets/images/product-images/'),
        ),
    ]
