# Generated by Django 4.2 on 2023-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_alter_productmodel_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
