# Generated by Django 4.2 on 2023-04-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_remove_productmodel_id_alter_productmodel_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productimage',
            field=models.ImageField(upload_to='media/static/assets/images/product-images/'),
        ),
    ]
