# Generated by Django 4.2 on 2023-05-13 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_alter_productmodel_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('billNo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('billDate', models.DateField(default=datetime.date.today)),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierPhone', models.CharField(max_length=12)),
                ('supplierGst', models.CharField(max_length=50)),
                ('paymentType', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierId', models.IntegerField(default=1001, primary_key=True, serialize=False)),
                ('supplierName', models.CharField(default='Not set', max_length=100)),
                ('supplierGst', models.CharField(default='Not set', max_length=100)),
                ('supplierAddress', models.CharField(default='Not set', max_length=100)),
                ('supplierEmail', models.CharField(default='Not set', max_length=100)),
                ('supplierPhone', models.CharField(default='Not set', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('pricePerUnit', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.purchases')),
            ],
            options={
                'verbose_name_plural': 'Purchased Products',
            },
        ),
    ]
