# Generated by Django 4.2 on 2023-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_purchases_suppliers_purchasedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productsize',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
