# Generated by Django 4.2 on 2023-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_alter_productmodel_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productimage',
            field=models.ImageField(null=True, upload_to='images/product-images'),
        ),
    ]
