# Generated by Django 4.2 on 2023-05-18 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_alter_productmodel_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerId', models.IntegerField(default=1001, primary_key=True, serialize=False)),
                ('customerName', models.CharField(default='Not set', max_length=100)),
                ('customerGst', models.CharField(default='Not set', max_length=100)),
                ('customerAddress', models.CharField(default='Not set', max_length=100)),
                ('customerEmail', models.CharField(default='Not set', max_length=100)),
                ('customerPhone', models.CharField(default='Not set', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('billNo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('billDate', models.DateField(default=datetime.date.today)),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=12)),
                ('customerGst', models.CharField(max_length=50)),
                ('paymentType', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sells',
            },
        ),
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('pricePerUnit', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.sells')),
            ],
            options={
                'verbose_name_plural': 'Sold Products',
            },
        ),
    ]
