# Generated by Django 4.2 on 2023-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_customers_sells_soldproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='gst',
            field=models.IntegerField(default=0),
        ),
    ]
