# Generated by Django 4.2 on 2023-05-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_purchases_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='grossTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='grossTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='gst',
            field=models.IntegerField(default=0),
        ),
    ]
