# Generated by Django 4.2 on 2023-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_purchases_grosstotal_sells_grosstotal_sells_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='quantity_sold',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
