# Generated by Django 4.2 on 2023-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0016_rename_productprice_productmodel_purchaseprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customerAddress',
            field=models.CharField(default='Not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplierAddress',
            field=models.CharField(default='Not available', max_length=100),
        ),
    ]
