# Generated by Django 4.2 on 2023-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0017_alter_customers_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='grossTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sells',
            name='grossTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sells',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sells',
            name='total',
            field=models.FloatField(),
        ),
    ]
