# Generated by Django 4.2 on 2023-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_alter_purchases_grosstotal_alter_purchases_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
