# Generated by Django 4.2 on 2023-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_purchases_otherexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='paidAmount',
            field=models.FloatField(default=0),
        ),
    ]
