# Generated by Django 4.2 on 2023-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_purchases_paidamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='paymentStatus',
            field=models.CharField(default='Paid', max_length=50),
        ),
    ]
