# Generated by Django 4.2 on 2023-06-04 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0022_purchases_paymentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierExpenses',
            fields=[
                ('billNo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('billDate', models.DateField(default=datetime.date.today)),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierPhone', models.CharField(max_length=12)),
                ('supplierGst', models.CharField(max_length=50)),
                ('paymentType', models.CharField(max_length=10)),
                ('total', models.FloatField()),
                ('gst', models.FloatField(default=0)),
                ('grossTotal', models.FloatField(default=0)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier Expenses',
            },
        ),
        migrations.CreateModel(
            name='SupplierExpensesProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('pricePerUnit', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.supplierexpenses')),
            ],
            options={
                'verbose_name_plural': 'Supplier Expenses Products',
            },
        ),
    ]
