# Generated by Django 4.2 on 2023-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0023_supplierexpenses_supplierexpensesproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierexpenses',
            name='expenseType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
