# Generated by Django 4.2 on 2023-06-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0026_customerexpenses_customerexpensesproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='billImage',
            field=models.ImageField(null=True, upload_to='images/purchase-bills'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='netTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='billImage',
            field=models.ImageField(null=True, upload_to='images/purchase-bills'),
        ),
        migrations.AddField(
            model_name='sells',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='netTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='otherExpenses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='paidAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='paymentStatus',
            field=models.CharField(default='Paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerexpensesproducts',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerexpensesproducts',
            name='pricePerUnit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='pricePerUnit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierexpensesproducts',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='supplierexpensesproducts',
            name='pricePerUnit',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='OtherExpensesOfSells',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expenseType', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.sells')),
            ],
            options={
                'verbose_name_plural': 'Other expenses of sells',
            },
        ),
        migrations.CreateModel(
            name='OtherExpensesOfPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expenseType', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.purchases')),
            ],
            options={
                'verbose_name_plural': 'Other expenses of purchases',
            },
        ),
    ]
