# Generated by Django 4.2 on 2023-06-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0027_purchases_billimage_purchases_nettotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='supplierId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='customerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='pricePerUnit',
            field=models.FloatField(default=0),
        ),
    ]
